baseURL = "https://ebridgeford.github.io/blog/"
languageCode = "en-us"
title = "A Silly Blog"
theme = "anatole"

[params]
title = "Eric's Blog"
author = "Eric Bridgeford"
profilePicture = "images/profile.jpg"
mainSections = ["posts"]


singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"


[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/eric-bridgeford-145340b4/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ebridgeford"
